# Generated by Django 5.2 on 2025-08-08 17:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Miembro"),
                            ("admin", "Admin"),
                            ("manager", "Gestor"),
                            ("auditor", "Auditor"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Activo"),
                            ("inactive", "Inactivo"),
                            ("suspended", "Suspendido"),
                            ("pending_approval", "Pendiente de Aprobación"),
                        ],
                        default="pending_approval",
                        max_length=20,
                    ),
                ),
                ("cedula", models.CharField(max_length=20, unique=True)),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("celular", models.CharField(blank=True, max_length=20, null=True)),
                ("direccion", models.TextField(blank=True, null=True)),
                ("ciudad", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "departamento",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "lugar_trabajo",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("cargo", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "salario_base",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("fecha_ingreso_cooperativa", models.DateField(blank=True, null=True)),
                (
                    "numero_asociado",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                (
                    "descuento_maximo_porcentaje",
                    models.DecimalField(decimal_places=2, default=30.0, max_digits=5),
                ),
                ("email_verified", models.BooleanField(default=False)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
    ]
